### ISSUE TITLE
Upgrade `fpdart` to `0.6.0`

### ISSUE THREAD

**Issue by getBoolean** [CodingSoot/modddels#15]
There is currently a dependency conflict with `modddels_annotation_fpdart` and latest `fpdart: ^0.6.0` because it uses `0.5.0`.

**Comment by CodingSoot** [comment]
Thanks for reporting ! Fixed with `modddels: 0.1.5` and `modddels_annotation_fpdart: 0.1.1`

**Comment by getBoolean** [comment]
That was fast, thanks!
